### ISSUE TITLE
Backups status incorrect given fresh configuration

### ISSUE THREAD

**Issue by clint-tseng** [opendatakit/central-frontend#184]
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/117762/49553551-14651680-f8ad-11e8-9497-f19f6c5f3541.png">

This result seems to violate the "If backups have been configured but no runs have happened since they were most recently set…" criteria in [this document](https://docs.google.com/document/d/1_J-u3ED46AmbwZC24gpYPp9dGnHGMYEWO3cBganuBuk/edit#).

**Comment by matthew-white** [comment]
Ah interesting. I think the issue has to do with how we identify which backup attempts correspond to the latest config. (Code [here](https://github.com/opendatakit/central-frontend/blob/b78c2ae5f3253ce43477ec98e241d36ecbab79d7/lib/components/backup/list.vue#L124-L143).) I think what's happening in the example above is that Frontend is categorizing those failed backup attempts as corresponding to the latest config. Failed backup attempts do not have a `configSetAt` property, which makes identifying which backup attempts correspond to the latest config slightly tricky, but I'm thinking that we can also use the `loggedAt` property to filter out attempts from before the latest config. Does that sound right? I think if I change the `recentForConfig()` method, the rest of the logic should still work.

**Comment by matthew-white** [comment]
After discussing with @clint-tseng, it does seem like it can't be guaranteed that `configSetAt` will be set for failed backup attempts. However, I think we can make use of `loggedAt` to address the example above and cases like it.

One case we haven't figured out is what happens if the config is changed while a backup is in progress. In that case, Frontend may associate a failed backup attempt with the wrong config. However, this case should be pretty unlikely. In case it does occur, we may want to take a conservative approach, reporting the failed backup attempt even if we're not sure whether it was a result of the most recent config or a result of a previous config.
