### ISSUE TITLE
Show custom alert message if user uploads form with duplicate field paths

### ISSUE THREAD

**Issue by matthew-white** [opendatakit/central-frontend#300]
Right now if the user tries to upload a form with duplicate field paths, Frontend shows an alert with the following message:

> A resource already exists with formDefId,path value(s) of 12345,/some/path.

Instead, let's show a custom alert message, something like:

> The Form definition you have uploaded contains two or more fields with the same path, /some/path.

**Comment by matthew-white** [comment]
@issa-tseng, what do you think the wording of the custom message should be?

**Comment by issa-tseng** [comment]
i'm not sure. i'm not even completely sure if we want to go down this path. i feel like we should either

1. bundle odk validate and run a full validation on every form as it comes in
2. suggest that the user runs odk validate in all cases like this rather than try to catch them all
3. do nothing

@lognaturel for opinion

**Comment by lognaturel** [comment]
I was initially in favor of a custom message but I think that was before I saw that it really shouldn't be happening anymore. I vote for doing nothing for now. If this is happening to users, it would be good for them to ask about it so we know that it's a pain point and that action is needed. Perhaps it would even be a useful thing to send to Sentry?

I expect that folks will generally use XLSForm support and that does run Validate.

**Comment by matthew-white** [comment]
Sounds good, I'll go ahead and close this issue for now!
