### ISSUE TITLE
New assets do not load without a hard refresh

### ISSUE THREAD

**Issue by issa-tseng** [opendatakit/central-frontend#76]
**See #140 for more context and how this issue relates to #77.**

Because the production server actually does static asset caching, browsers will not load new versions of the JS/CSS/etc unless a hard refresh (shift+reload) is performed. This will likely confuse people, and could cause problems with server/client mismatch after deploys.

References to assets in the HTML file need `?somethingunique` appended to them to resolve this, much like what icomoon does.

**Comment by clint-tseng** [comment]
Just as an update, I know that I'd mentioned briefly that I might have the docker build do this, but having looked at it I think this should still be accomplished alongside #77 as part of the build script specific to this project.

That way the index.html file gets transformed and the resulting file is placed in `dist/` or whatever, instead of... whatever spiderweb work it would take to make it work as-is.

You can take a look at https://github.com/xyonix/vannot/blob/master/project/build/html.js to see how I did this particular task for another project; bonus points for using the short-sha as the bust id instead of the timestamp but tbh the timestamp is fine too.

**Comment by matthew-white** [comment]
This should be resolved by #217.
